table _Measures_LaborPlanning
	lineageTag: bfa928cb-8e10-48eb-ad4c-8d742fcd74af

	measure 'Total Actual Hours' = SUM('Fct_LaborRollups'[Hours_Total])
		formatString: #,##0.00
		displayFolder: 1. Efficiency & Cost
		lineageTag: 82e7b5eb-91d4-4517-98d1-575202f8fa62

	measure 'Total OT Hours' = SUM('Fct_LaborRollups'[Hours_OT_Total])
		formatString: #,##0.00
		displayFolder: 1. Efficiency & Cost
		lineageTag: a92e90af-b004-4f30-9c31-f7a24d36594b

	measure 'Network OT %' = DIVIDE([Total OT Hours], [Total Actual Hours], 0)
		formatString: 0.00%
		displayFolder: 1. Efficiency & Cost
		lineageTag: 636058ff-2fd8-4e4f-9aa0-a24771ec1928

	measure 'Gross Units' = SUM('Fct_LaborRollups'[Units_Gross])
		formatString: #,##0
		displayFolder: 1. Efficiency & Cost
		lineageTag: 134c81f0-e843-472f-9573-bdd22308e82f

	measure 'Blended PPH' = DIVIDE([Gross Units], [Total Actual Hours], 0)
		formatString: 0.00
		displayFolder: 1. Efficiency & Cost
		lineageTag: 61a56c35-e361-42f7-9e96-8628e28eb893

	measure 'Current Working HC' = SUM('Fct_HR_Parameters'[Working_HC])
		formatString: #,##0
		displayFolder: 2. Headcount Control
		lineageTag: 86ef10ee-e33e-4551-ad47-5ab612329114

	measure 'Target HC' = SUM('Fct_HR_Parameters'[Target_HC])
		formatString: #,##0
		displayFolder: 2. Headcount Control
		lineageTag: 0ef291d4-69f2-4e26-9675-5d12f5a7548c

	measure 'Total HC Gap' = [Target HC] - [Current Working HC]
		formatString: #,##0
		displayFolder: 2. Headcount Control
		lineageTag: 0bfdd4b0-bd0c-4e67-b475-cdcf8d1c8ee2

	measure '13-Week Rolling TO Rate' =
			CALCULATE(
			    DIVIDE(SUM('Fct_HR_Parameters'[Terminations]), [Current Working HC], 0),
			    DATESINPERIOD('Dim_Calendar'[Date], MAX('Dim_Calendar'[Date]), -13, WEEK)
			)
		formatString: 0.00%
		displayFolder: 3. Recruiting Planning
		lineageTag: e61be2c8-e0f2-47eb-a50b-3dea2834c9ad

	measure 'Forecasted Terminations (60 Days)' = INT([Current Working HC] * [13-Week Rolling TO Rate] * (8.57 / 13))
		formatString: #,##0
		displayFolder: 3. Recruiting Planning
		lineageTag: d7d226cf-1874-46f8-9137-d1e80a89e443

	measure '60-Day Recruiting Need' = [Total HC Gap] + [Forecasted Terminations (60 Days)]
		formatString: #,##0
		displayFolder: 3. Recruiting Planning
		lineageTag: cee38405-f4fe-4a59-88ed-3ed2e52ad35a

	measure 'Active Requisitions (Hiring)' = SUM('Fct_HR_Parameters'[Hires])
		formatString: #,##0
		displayFolder: 3. Recruiting Planning
		lineageTag: c2e4d682-50b8-4a54-9905-fddb620da941

	measure 'OT Alert Flag' = ```
			IF([Network OT %] > 0.15, 
			    "🚨 High OT Risk (" & FORMAT([Network OT %], "0.0%") & ")", 
			    BLANK()
			)
			```
		displayFolder: 4. Audit & Alerts
		lineageTag: 30058685-9c7c-4773-8457-1b49866f8ee7

	column Column1
		dataType: string
		isHidden
		lineageTag: 7a578bd2-578e-41f3-8340-05670da3e869
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition _Measures_LaborPlanning = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

