table _Measures_LaborPlanning
	lineageTag: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d

	measure Actual_PPH_Avg =
			CALCULATE(
			            AVERAGE('Fct_LaborRollups'[NonYard_PPH]),
			            REMOVEFILTERS('Dim_Calendar')
			        )
		formatString: 0.00
		displayFolder: 01. Core Base
		lineageTag: d21dc543-4644-4853-a0f9-8e7d30bd420f

	measure Current_Working_HC =
			VAR Max_Actual_Date = CALCULATE(MAX('Fct_LaborRollups'[WeekEnding]), REMOVEFILTERS('Dim_Calendar'))
			        RETURN
			        CALCULATE(
			            SUM('Fct_LaborRollups'[Headcount_Total]),
			            REMOVEFILTERS('Dim_Calendar'),
			            'Dim_Calendar'[Date] = Max_Actual_Date
			        )
		formatString: #,0
		displayFolder: 01. Core Base
		lineageTag: 338d6768-b4c1-48d8-895f-c8e425ba36f8

	measure Total_OB_Volume = ```
			CALCULATE(
			            SUM('OB Delta Split'[Bill-ECOMM]) + 
			            SUM('OB Delta Split'[Ecomm])
			        )
			```
		formatString: #,0
		displayFolder: 01. Core Base
		lineageTag: 4a69f57a-565c-4d70-b1a6-94ac67b3cf9c

	measure Total_IB_Volume = ```
			CALCULATE(
			            SUM('Fct_ReceiptsSQL'[PurchaseOrderPcs]) + 
			            SUM('Fct_ReceiptsSQL'[TransferInPcs])
			        )
			```
		formatString: #,0
		displayFolder: 01. Core Base
		lineageTag: 7ef334d6-ee20-408a-9cc2-f11ab687449b

	measure Required_HC_Target = ```
			SUMX(
			            VALUES('Fct_LaborRollups'[Department_Desc]),
			            
			            VAR Current_Dept = MAX('Fct_LaborRollups'[Department_Desc])
			            
			            VAR Avg_Weekly_OB_Volume = AVERAGEX(VALUES('Dim_Calendar'[SaturdayDate]), [Total_OB_Volume])
			            VAR Avg_Weekly_IB_Volume = AVERAGEX(VALUES('Dim_Calendar'[SaturdayDate]), [Total_IB_Volume])
			            VAR Dept_PPH = [Actual_PPH_Avg]
			            
			            VAR Target_HC = 
			                SWITCH(TRUE(),
			                    Current_Dept = "Shipping" || Current_Dept = "Ecomm", DIVIDE(Avg_Weekly_OB_Volume, (Dept_PPH * 40)),
			                    Current_Dept = "Receiving" || Current_Dept = "Inbound", DIVIDE(Avg_Weekly_IB_Volume, (Dept_PPH * 40)),
			                    BLANK()
			                )
			            RETURN Target_HC
			        )
			```
		formatString: #,0.0
		displayFolder: 02. Core Engines
		lineageTag: 78e673dc-2bc4-45ef-9759-7369694e67dd

	measure Net_HC_Gap = ```
			VAR Current_Site = MAX('Dim_DCs'[wh_id]) 
			        VAR Avg_Site_Absenteeism = CALCULATE(
			            AVERAGE('Fct_Location_Dept_HR_Parameters'[Target_Absenteeism_Pct]),
			            'Fct_Location_Dept_HR_Parameters'[wh_id] = Current_Site
			        )
			        VAR Final_Absenteeism = COALESCE(Avg_Site_Absenteeism, 0.10) 
			        VAR Site_Effective_HC = [Current_Working_HC] * (1 - Final_Absenteeism)
			        
			        RETURN [Required_HC_Target] - Site_Effective_HC
			```
		formatString: #,0.0
		displayFolder: 02. Core Engines
		lineageTag: 325be840-779b-467b-b779-a76f7960857f

	measure Capacity_40_Hrs = [Current_Working_HC] * [Actual_PPH_Avg] * 40
		formatString: #,0
		displayFolder: 03. DC Quickviews
		lineageTag: d2143119-549b-4593-a97b-9de2bf2098fb

	measure Capacity_45_Hrs = [Current_Working_HC] * [Actual_PPH_Avg] * 45
		formatString: #,0
		displayFolder: 03. DC Quickviews
		lineageTag: 82230278-9535-409c-93ff-20c7de035c19

	measure Capacity_50_Hrs = [Current_Working_HC] * [Actual_PPH_Avg] * 50
		formatString: #,0
		displayFolder: 03. DC Quickviews
		lineageTag: 85f395b6-5851-4b8f-a9dd-616e560b5f0e

	measure Capacity_55_Hrs = [Current_Working_HC] * [Actual_PPH_Avg] * 55
		formatString: #,0
		displayFolder: 03. DC Quickviews
		lineageTag: 2729d0df-d252-4105-a26f-4675054629ea

	measure Ratio_OB_vs_IB = DIVIDE([Total_OB_Volume], [Total_IB_Volume], BLANK())
		formatString: 0.0%
		displayFolder: 03. DC Quickviews
		lineageTag: 970ddeab-d442-4fb5-8c09-61fefbc7caf1

	measure Dynamic_Adj_OB_Volume = ```
			
			// 直接抓取单量滑动条，没拉动就默认是 0
			VAR Current_Adj = SELECTEDVALUE('FCST_Adj_Pct'[FCST_Adj_Pct], 0)
			RETURN 
			[Total_OB_Volume] * (1 + Current_Adj)
			```
		formatString: #,0
		displayFolder: 02. Core Engines
		lineageTag: d214efbd-92c2-43a3-9d04-934c4ab09a55

	measure Dynamic_Adj_IB_Volume = ```
			
			VAR Current_Adj = SELECTEDVALUE('FCST_Adj_Pct'[FCST_Adj_Pct], 0)
			RETURN 
			[Total_IB_Volume] * (1 + Current_Adj)
			```
		formatString: #,0
		displayFolder: 02. Core Engines
		lineageTag: 993d673d-851b-49ad-b890-9ea98ce40796

	measure Mix_Ecomm_Pct = DIVIDE(CALCULATE(SUM('Fct_DemandFulfillmentSQL'[DemandFulfillment]), 'Fct_DemandFulfillmentSQL'[Channel] = "Ecomm"), [Total_OB_Volume])
		formatString: 0.0%
		displayFolder: 01. Core Base
		lineageTag: 2049e35f-1f65-4e48-9f1c-3476347f447f

	measure Dynamic_Required_HC = ```
			
			SUMX(
			    VALUES('Fct_LaborRollups'[Department_Desc]),
			    
			    VAR Current_Dept = MAX('Fct_LaborRollups'[Department_Desc])
			    VAR Ecomm_Pct = [Mix_Ecomm_Pct]
			    VAR Billable_Pct = 1 - Ecomm_Pct
			    
			    // 动态调整后的单量分摊
			    VAR Dept_Volume = 
			        SWITCH(TRUE(),
			            Current_Dept = "Ecomm", [Dynamic_Adj_OB_Volume] * Ecomm_Pct,
			            Current_Dept = "Shipping", [Dynamic_Adj_OB_Volume] * Billable_Pct,
			            Current_Dept = "Receiving" || Current_Dept = "Inbound", [Dynamic_Adj_IB_Volume],
			            BLANK()
			        )
			    
			    VAR Dept_PPH = [Actual_PPH_Avg]
			    
			    // 💡 绝对防御：直接在这里抓取工时滑动条，没拉动就默认 40H
			    VAR Target_Hrs = SELECTEDVALUE('Target_Hours'[Target_Hours], 40) 
			    
			    RETURN DIVIDE(Dept_Volume, (Dept_PPH * Target_Hrs))
			)
			```
		displayFolder: 02. Core Engines
		lineageTag: 547ebec1-d22f-40d3-8a41-a85b2a68f43f

	partition _Measures_LaborPlanning = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

