table _Measures_LaborPlanning
	lineageTag: bfa928cb-8e10-48eb-ad4c-8d742fcd74af

	measure 'Total Actual Hours' = SUM('Fct_LaborRollups'[Hours_Total])
		formatString: #,##0.00
		displayFolder: 1. Efficiency & Cost
		lineageTag: 82e7b5eb-91d4-4517-98d1-575202f8fa62

	measure 'Total OT Hours' = SUM('Fct_LaborRollups'[Hours_OT_Total])
		formatString: #,##0.00
		displayFolder: 1. Efficiency & Cost
		lineageTag: a92e90af-b004-4f30-9c31-f7a24d36594b

	measure 'Network OT %' = DIVIDE([Total OT Hours], [Total Actual Hours], 0)
		formatString: 0.00%
		displayFolder: 1. Efficiency & Cost
		lineageTag: 636058ff-2fd8-4e4f-9aa0-a24771ec1928

	measure 'Gross Units' = SUM('Fct_LaborRollups'[Units_Gross])
		formatString: #,##0
		displayFolder: 1. Efficiency & Cost
		lineageTag: 134c81f0-e843-472f-9573-bdd22308e82f

	measure 'Blended PPH' = DIVIDE([Gross Units], [Total Actual Hours], 0)
		formatString: 0.00
		displayFolder: 1. Efficiency & Cost
		lineageTag: 61a56c35-e361-42f7-9e96-8628e28eb893

	measure 'Current Working HC' = SUM('Fct_HR_Parameters'[Working_HC])
		formatString: #,##0
		displayFolder: 2. Headcount Control
		lineageTag: 86ef10ee-e33e-4551-ad47-5ab612329114

	measure 'Target HC' = SUM('Fct_HR_Parameters'[Target_HC])
		formatString: #,##0
		displayFolder: 2. Headcount Control
		lineageTag: 0ef291d4-69f2-4e26-9675-5d12f5a7548c

	measure 'Total HC Gap' = [Target HC] - [Current Working HC]
		formatString: #,##0
		displayFolder: 2. Headcount Control
		lineageTag: 0bfdd4b0-bd0c-4e67-b475-cdcf8d1c8ee2

	measure '13-Week Rolling TO Rate' =
			CALCULATE(
			    DIVIDE(SUM('Fct_HR_Parameters'[Terminations]), [Current Working HC], 0),
			    DATESINPERIOD('Dim_Calendar'[Date], MAX('Dim_Calendar'[Date]), -13, WEEK)
			)
		formatString: 0.00%
		displayFolder: 3. Recruiting Planning
		lineageTag: e61be2c8-e0f2-47eb-a50b-3dea2834c9ad

	measure 'Forecasted Terminations (60 Days)' = INT([Current Working HC] * [13-Week Rolling TO Rate] * (8.57 / 13))
		formatString: #,##0
		displayFolder: 3. Recruiting Planning
		lineageTag: d7d226cf-1874-46f8-9137-d1e80a89e443

	measure '60-Day Recruiting Need' = [Total HC Gap] + [Forecasted Terminations (60 Days)]
		formatString: #,##0
		displayFolder: 3. Recruiting Planning
		lineageTag: cee38405-f4fe-4a59-88ed-3ed2e52ad35a

	measure 'Active Requisitions (Hiring)' = SUM('Fct_HR_Parameters'[Hires])
		formatString: #,##0
		displayFolder: 3. Recruiting Planning
		lineageTag: c2e4d682-50b8-4a54-9905-fddb620da941

	measure 'OT Alert Flag' = ```
			IF([Network OT %] > 0.15, 
			    "🚨 High OT Risk (" & FORMAT([Network OT %], "0.0%") & ")", 
			    BLANK()
			)
			```
		displayFolder: 4. Audit & Alerts
		lineageTag: 30058685-9c7c-4773-8457-1b49866f8ee7

	measure Dynamic_Required_HC = ```
			
			SUMX(
			    VALUES('Fct_LaborRollups'[Department_Desc]),
			    
			    VAR Current_Dept = MAX('Fct_LaborRollups'[Department_Desc])
			    VAR Ecomm_Pct = [Mix_Ecomm_Pct]
			    VAR Billable_Pct = 1 - Ecomm_Pct
			    
			    // 1. 动态单量
			    VAR Dept_Volume = 
			        SWITCH(TRUE(),
			            Current_Dept = "Ecomm", [Total_OB_Volume] * (1 + SELECTEDVALUE('FCST_Adj_Pct'[FCST_Adj_Pct], 0)) * Ecomm_Pct,
			            Current_Dept = "Shipping", [Total_OB_Volume] * (1 + SELECTEDVALUE('FCST_Adj_Pct'[FCST_Adj_Pct], 0)) * Billable_Pct,
			            // 👇 这里修复了！必须写两遍 Current_Dept = 
			            Current_Dept = "Receiving" || Current_Dept = "Inbound", [Total_IB_Volume],
			            BLANK()
			        )
			    
			    // 2. 获取效率，如果底层数据是空或0，强制给个保底值(例如 15) 防止报错
			    VAR Raw_PPH = [Actual_PPH_Avg]
			    VAR Dept_PPH = IF(ISBLANK(Raw_PPH) || Raw_PPH = 0, 15, Raw_PPH) 
			    
			    // 3. 🎯 核心接线：强制抓取切片器！如果没选，默认 40
			    VAR Target_Hrs = SELECTEDVALUE('Target_Hours'[Target_Hours], 40) 
			    
			    // 安全除法：如果还是除以 0，返回空白而不是 Infinity
			    RETURN DIVIDE(Dept_Volume, (Dept_PPH * Target_Hrs), BLANK())
			)
			```
		lineageTag: 9bd5f598-0f9d-4525-8e63-a77674be5584

	column Column1
		dataType: string
		isHidden
		lineageTag: 7a578bd2-578e-41f3-8340-05670da3e869
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition _Measures_LaborPlanning = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

